### ISSUE TITLE
No issue, just an idea

### ISSUE THREAD

**Issue by gurolayanlar** [code-with-max/godot-google-play-iapp#15]
If any problem occurs, applying it as follows may give better results.

![Untitled-1](https://github.com/user-attachments/assets/197e6cdc-3167-40a5-8352-dbd68dbe9c72)

![Untitled-2](https://github.com/user-attachments/assets/a9d13c28-86e9-44fa-bbb9-421a7a23f000)

**Comment by code-with-max** [comment]
@gurolayanlar 
You're right, I wrote this example quickly, without thinking about optimization. But I have always held the opinion that developers who will use the plugin have the right to do it as they see fit for themselves.

Thanks for the idea. 

I also suggest looking at another example of order processing, which I implemented in one of my applications.

https://gist.github.com/code-with-max/56881cbb3796a19a68d8eabd819d6ff7

**Comment by gurolayanlar** [comment]
Thank you again for your interest and open opinions.
